# turbo / home Mac — `brew leaves` on turbo, 2026-08-30
brew "autossh"
brew "caddy"
brew "emacs"
brew "ffmpeg"
brew "gh"
brew "herdr"
brew "mkcert"
brew "node"
brew "pipx"
brew "python@3.13"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "tmux"
brew "whisper-cpp"
brew "xcodegen"
brew "yt-dlp"
